FROM nerevarishe/vista-portal-frontend:dev as build
WORKDIR /srv/vista-portal-frontend
COPY . .
RUN npm run build


FROM nginx:alpine
COPY --from=build /srv/vista-portal-frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
